### ISSUE TITLE
this code could return nil and panic

### ISSUE THREAD

**Issue by barnettZQG** [kevinburke/ssh_config#21]
https://github.com/kevinburke/ssh_config/blob/4fcc689beeab13c6dd7ab1d65cb9d7a1aeea9663/parser.go#L98

**Comment by kevinburke** [comment]
Do you have an example config file that panics? I think the lexer checks for this, I can't write a config file that panics.

**Comment by bricewge** [comment]
Looks like I got one here! It is triggered if the config file doesn't have a return carried at it's end, like this one:
```
$ cat -e ~/.ssh/config
Host example$
  HostName example.com$
  Port 4242
```
And here is the log:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x84bb6c5]

goroutine 29 [running]:
cesanta.com/vendor/github.com/kevinburke/ssh_config.decode.func1(0x1b4d53dc)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/config.go:216 +0x1b8
panic(0x87a9960, 0x8c70888)
        /usr/lib/go-1.10/src/runtime/panic.go:502 +0x1dc
cesanta.com/vendor/github.com/kevinburke/ssh_config.(*sshParser).parseKV(0x1b3b24b0, 0x1b1ce530)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/parser.go:99 +0x195
cesanta.com/vendor/github.com/kevinburke/ssh_config.(*sshParser).(cesanta.com/vendor/github.com/kevinburke/ssh_config.parseKV)-fm(0x1b1ce530)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/parser.go:80 +0x20
cesanta.com/vendor/github.com/kevinburke/ssh_config.(*sshParser).run(0x1b3b24b0)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/parser.go:38 +0x33
cesanta.com/vendor/github.com/kevinburke/ssh_config.parseSSH(0x1b1faa00, 0x1b2e0000, 0x1b1faa00)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/parser.go:182 +0x296
cesanta.com/vendor/github.com/kevinburke/ssh_config.decode(0x88ffc20, 0x1b2e0400, 0x1b2e0000, 0x0, 0x0, 0x0)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/config.go:226 +0x85
cesanta.com/vendor/github.com/kevinburke/ssh_config.parseWithDepth(0x1b2f7880, 0x1a, 0x8845400, 0x0, 0x0, 0x0)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/config.go:198 +0xa6
cesanta.com/vendor/github.com/kevinburke/ssh_config.parseFile(0x1b2f7880, 0x1a, 0x806e770, 0x1b2d80ac, 0x1b4d5434)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/config.go:189 +0x2e
cesanta.com/vendor/github.com/kevinburke/ssh_config.(*UserSettings).GetStrict.func1()
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/config.go:158 +0x42
sync.(*Once).Do(0x8c74ed4, 0x1b4d5468)
        /usr/lib/go-1.10/src/sync/once.go:44 +0xb0
cesanta.com/vendor/github.com/kevinburke/ssh_config.(*UserSettings).GetStrict(0x8c74ec0, 0x1b1fb38c, 0xb, 0x8849448, 0x8, 0x1b2e03d8, 0x1b0e4940, 0x1b3b2370, 0x1b2e03e0)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/config.go:149 +0x40
cesanta.com/vendor/github.com/kevinburke/ssh_config.(*UserSettings).Get(0x8c74ec0, 0x1b1fb38c, 0xb, 0x8849448, 0x8, 0x8093d90, 0x1b1b2000)
        /go/src/cesanta.com/vendor/github.com/kevinburke/ssh_config/config.go:134 +0x41
cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).doGetHostWithPortFromSSHConfig(0x1b160420, 0x0, 0x0, 0x0)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:155 +0x6b
cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).getHostWithPort(0x1b160420, 0x1b4fa540, 0x0)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:134 +0x25
cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).connect(0x1b160420, 0x0, 0xb)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:118 +0x75
cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*runner).Command(0x1afaf7c8, 0x884fc5d, 0xf, 0x1b1603f0, 0x0, 0x0, 0x1b1fb386, 0x1afb6cf0, 0x1b1fb3a1, 0x0)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:50 +0x82
cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).newSession(0x1afaf7d0, 0x884fc5d, 0xf, 0x1b1603f0, 0x0, 0x0, 0x0, 0x0, 0x1b1603f0)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:112 +0x52
cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).NewUploadPackSession(0x1afaf7d0, 0x1b1603f0, 0x0, 0x0, 0x1b1603f0, 0x0, 0x0, 0x1af0e068)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:89 +0x4b
cesanta.com/vendor/gopkg.in/src-d/go-git%2ev4.newUploadPackSession(0x1b1fb380, 0x35, 0x0, 0x0, 0x1b160390, 0x1b0e4890, 0x8057dc8, 0x1b0e4890)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/remote.go:321 +0x7d
cesanta.com/vendor/gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0x1b0e4890, 0x8904da0, 0x1afba030, 0x1b4d5748, 0x0, 0x0, 0x0, 0x0)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/remote.go:259 +0xe9
cesanta.com/vendor/gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0x1b1586e0, 0x8904da0, 0x1afba030, 0x1b4d5748, 0x88455d2, 0x4, 0x8908ac0, 0x1b0e4160, 0x8908ac0)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/repository.go:650 +0x8a
cesanta.com/vendor/gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0x1b1586e0, 0x8904da0, 0x1afba030, 0x1b1cc280, 0x0, 0x0)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/repository.go:521 +0x1ed
cesanta.com/vendor/gopkg.in/src-d/go-git%2ev4.PlainCloneContext(0x8904da0, 0x1afba030, 0x1b1fa2c0, 0x3e, 0x8057400, 0x1b1cc280, 0x88ffca0, 0x1b03c260, 0x1b1cc280)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/repository.go:353 +0x7e
cesanta.com/vendor/gopkg.in/src-d/go-git%2ev4.PlainClone(0x1b1fa2c0, 0x3e, 0x0, 0x1b1cc280, 0x88ffca0, 0x1b03c240, 0x8f76e68)
        /go/src/cesanta.com/vendor/gopkg.in/src-d/go-git.v4/repository.go:337 +0x4e
cesanta.com/common/go/ourgit.(*ourGitGoGit).Clone(0x8f76a68, 0x1b1fa340, 0x35, 0x1b1fa2c0, 0x3e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/cesanta.com/common/go/ourgit/ourgit_gogit.go:286 +0x190
cesanta.com/mos/build.prepareLocalCopyGit(0x1b1fa340, 0x35, 0x1b109878, 0x5, 0x1b1fa2c0, 0x3e, 0x88ff6a0, 0x1b0e43d0, 0x1, 0x185c5000, ...)
        /go/src/cesanta.com/mos/build/swmodule.go:464 +0x16b4
cesanta.com/mos/build.(*SWModule).PrepareLocalDir(0x1b3b2030, 0x1b38e2d0, 0x2e, 0x88ff6a0, 0x1b0e43d0, 0x88fe901, 0x1b109878, 0x5, 0x185c5000, 0x1a3, ...)
        /go/src/cesanta.com/mos/build/swmodule.go:194 +0x201
main.(*compProviderReal).GetLibLocalPath(0x1b0e4420, 0x1b3b2030, 0x1afb8ab0, 0x29, 0x1b109878, 0x5, 0x1af2c4ed, 0x5, 0x0, 0x0, ...)
        /go/src/cesanta.com/mos/build.go:1492 +0x2d0
cesanta.com/mos/manifest_parser.prepareLib(0x0, 0x0, 0x1afa4dc0, 0x35, 0x1afa4dc0, 0x35, 0x0, 0x0, 0x1afa4de2, 0xf, ...)
        /go/src/cesanta.com/mos/manifest_parser/manifest_parser.go:593 +0x317
created by cesanta.com/mos/manifest_parser.readManifestWithLibs2
        /go/src/cesanta.com/mos/manifest_parser/manifest_parser.go:534 +0x1f1
```

**Comment by kevinburke** [comment]
Ah, perfect, I can reproduce now! A little tricky to write a file without a trailing newline on Macs.
